### ISSUE TITLE
training data prepare

### ISSUE THREAD

**Issue by mozoltov183** [mtkresearch/clairaudience#2]
Hi, I wnat to train model use GigaSpeech now,  the Guidance doc said  **ensure that Gigaspeech medium is downladed to data/hf_dd_data/gigaspeech/m**，i don’t know which format is available，origin long wav ? or short wav slice according to segments (timestamp json file)?
moreover，what means of `dataset_name ` in func `setup_dataset ` (data_process.py);
line 94: `elif dataset_name == gigaspeech:`
line 101: `elif dataset_name == gigaspeech_extracted:`
line 115:  `elif dataset_name == gigaspeech:`

thx！

**Comment by Snow9666** [comment]
Did you figure it out?
